### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by Suolumi** [TomC17/Steam-Deck-Themes#4]
Hello, i just love art hero but is there a way to have the default theme with art hero enabled? So far no success on my own

**Comment by TomC17** [comment]
Hi, glad you're enjoying Art Hero! It's possible yeah, I'll look into it today, it'll need to be either a new theme altogether or an option.

Just to be clear though, can you describe what exactly you're looking for? I'm assuming no obsidian integration or the like, just lowered box art and the clean hero art?

**Comment by Suolumi** [comment]
Hi, no problem at all with obsidian since i can just disable it, but art hero comes with a theme on its own, Black by default, which you can change to blue/white/red or any other color you've made. The only problem i have is that you need to select a theme, and cannot keep the default SteamOS one. So you could maybe add a Default option along with the theme colors? Thank you in advance

**Comment by TomC17** [comment]
Pushed an update to the website for the new version. Might take a while for someone to get around to approving it though. If you know github you can grab the version from this repo though.
